### ISSUE TITLE
TwitterSystemProvider ..  deprecated?

### ISSUE THREAD

**Issue by bbookman** [rubygarage/authorize-me#6]
I have implemented code and see this when clicking the button in my UI that would trigger the code
```
    @IBAction func systemButtonPressed(_ sender: Any) {
        provider = TwitterSystemProvider()
        authorizeMe()
    }
```

> AuthorizeMe] The identifiers for system account types were deprecated
> Problem with provider

**Comment by plzen** [comment]
TwitterSystemProvider is deprecated because Apple removed supporting Facebook, Twitter, Vimeo, Flickr system accounts in iOS 11. You can use this type of accounts with iOS 10.

More details here - http://appleinsider.com/articles/17/06/05/apple-drops-twitter-facebook-flickr-vimeo-integration-in-ios-11

**Comment by bbookman** [comment]
So that means you don't support Twitter now?

**Comment by plzen** [comment]
It's deprecated because iOS 11 doesn't support system accounts. But you can use it in iOS < 11.
